#!/usr/bin/env bash
# /usr/bin/froyo src/array.fy -oarray -ywerror -ynoticeFroyo -ycomments
# Arrays in Froyo
# For testing the compiler can properly handle arrays
# define array
declare -r myArray=('firstItem' 'secondItem' 'thirdItem')
echo "first =" ${myArray[0]}
echo "third =" ${myArray[2]}
