#!/usr/bin/env bash
# ../froyo src/array.fy -oarray -ywerror -ynoticeFroyo -ycomments -w
# Arrays in Froyo
# For testing the compiler can properly handle arrays
# define array
declare -r myArray=('firstItem' 'secondItem' 'thirdItem')
echo "first =" $[0]myArray
echo "third =" $[2]myArray
echo "all =" $[@]myArray
