#!/usr/bin/env bash
# /usr/bin/froyo src/wrong.fy -owrong -ywerror -ynoerror -ynoticeFroyo -ycomments
# This file is purposely wrong to test if Froyo
# can spot its errors or not
declare -r thisInteger=notaninteger
declare -r thisFloat=x.y.z
declare -r thisBoolean=itstrue
declare -r thisCharacter=ab
declare -r thisArray=(first second third)
echo $thisInteger
echo ($thisFloat)
echo $thisBoolean

fn myFunction) firstArg
}
