name: make-deb

on:
  push:
    paths:
      - 'froyo'
      - 'input_files/src/**'
      - 'ext/src/**'
      - 'pkg/src/make-deb.fy'
      - 'pkg/DEBIAN'
      - '.github/workflows/make-deb.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: alemontn/froyo
          path: /home/runner/work/froyo/froyo

      - name: Make debian package
        env:
          GH_WORKFLOW: 1
        run: |
          cd /home/runner/work/froyo/froyo/pkg
          ./make-deb.sh
          mv deb/build.deb ~/froyo.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: /home/runner/froyo.deb
